Title: '#5d6d7e&lPrice Settings'
Size: 27
Inventory_Type: CHEST
Use_Mini_Message: false

Format:
  Lore:
    Price:
      BUY:
        FLAT:
          - '#fffc9a▪ #ddeceeCurrent: #fffc9a%product_price_buy%'
          - ''
          - '#ddeceePrice for players to #fffc9apurchase#ddecee this item.'
          - ''
          - '#9af7ff&lActions:'
          - '#9af7ff▪ #ddeceeLeft-Click: #9af7ffChange'
          - '#ff9a9a▪ #ddecee[Q/Drop] Key: #ff9a9aDisable'
        FLOAT:
          - '#fffc9a▪ #ddeceeMinimal: #fffc9a%product_pricer_buy_min%'
          - '#fffc9a▪ #ddeceeMaximal: #fffc9a%product_pricer_buy_max%'
          - ''
          - '#ddeceeRange of values to generate'
          - '#ddeceepurchase price from.'
          - ''
          - '#9af7ff&lActions:'
          - '#9af7ff▪ #ddeceeLeft-Click: #9af7ffChange'
          - '#ff9a9a▪ #ddecee[Q/Drop] Key: #ff9a9aDisable'
        DYNAMIC:
          - '#fffc9a▪ #ddeceeMinimal: #fffc9a%product_pricer_buy_min%'
          - '#fffc9a▪ #ddeceeMaximal: #fffc9a%product_pricer_buy_max%'
          - ''
          - '#ddeceeRange of values to limit'
          - '#ddeceemin. and max. purchase price.'
          - '#ddecee(it will never exceed these values)'
          - ''
          - '#9af7ff&lActions:'
          - '#9af7ff▪ #ddeceeLeft-Click: #9af7ffChange'
          - '#ff9a9a▪ #ddecee[Q/Drop] Key: #ff9a9aDisable'
      SELL:
        FLAT:
          - '#fffc9a▪ #ddeceeCurrent: #fffc9a%product_price_sell%'
          - ''
          - '#ddeceePrice for players to #fffc9asell#ddecee this item.'
          - ''
          - '#9af7ff&lActions:'
          - '#9af7ff▪ #ddeceeLeft-Click: #9af7ffChange'
          - '#ff9a9a▪ #ddeceeRight-Click: #ff9a9aDisable'
        FLOAT:
          - '#fffc9a▪ #ddeceeMinimal: #fffc9a%product_pricer_sell_min%'
          - '#fffc9a▪ #ddeceeMaximal: #fffc9a%product_pricer_sell_max%'
          - ''
          - '#ddeceeRange of values to generate'
          - '#ddeceesell price from.'
          - ''
          - '#9af7ff&lActions:'
          - '#9af7ff▪ #ddeceeLeft-Click: #9af7ffChange Min'
          - '#9af7ff▪ #ddeceeRight-Click: #9af7ffChange Max'
        DYNAMIC:
          - '#fffc9a▪ #ddeceeMinimal: #fffc9a%product_pricer_sell_min%'
          - '#fffc9a▪ #ddeceeMaximal: #fffc9a%product_pricer_sell_max%'
          - ''
          - '#ddeceeRange of values to limit'
          - '#ddeceemin. and max. sell price.'
          - '#ddecee(it will never exceed these values)'
          - ''
          - '#9af7ff&lActions:'
          - '#9af7ff▪ #ddeceeLeft-Click: #9af7ffChange Min'
          - '#9af7ff▪ #ddeceeRight-Click: #9af7ffChange Max'

Content:
  return:
    Priority: 5
    Slots: 22
    Type: RETURN
    Item:
      Material: PLAYER_HEAD
      Head_Texture: eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvYmU5YWU3YTRiZTY1ZmNiYWVlNjUxODEzODlhMmY3ZDQ3ZTJlMzI2ZGI1OWVhM2ViNzg5YTkyYzg1ZWE0NiJ9fX0=
      Name: '#e3fbf9(↓) &lReturn'

  PRODUCT_CHANGE_CURRENCY:
    Priority: 5
    Slots: 3
    Type: PRODUCT_CHANGE_CURRENCY
    Item:
      Material: PLAYER_HEAD
      Head_Texture: 'eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvYjg4OWNmY2JhY2JlNTk4ZThhMWNkODYxMGI0OWZjYjYyNjQ0ZThjYmE5ZDQ5MTFkMTIxMTM0NTA2ZDhlYTFiNyJ9fX0='
      Name: '#fffc9a&lCurrency'
      Lore:
        - '#fffc9a▪ #ddeceeCurrent: #fffc9a%product_currency%'
        - ''
        - '#ffeea2[▶] #ddeceeLeft-Click to #ffeea2change#ddecee.'

  PRODUCT_CHANGE_PRICE_TYPE:
    Priority: 5
    Slots: 5
    Type: PRODUCT_CHANGE_PRICE_TYPE
    Item:
      Material: PLAYER_HEAD
      Head_Texture: 'eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNmI5Mjk5YjcyNGM1ZDM0YWM5M2VkZTc1NjAxZGZlYjBiZGE1NzhkNzBiOGY0ZDdmODJkNzY3NmYwYzZjMTE0YSJ9fX0='
      Name: '#fffc9a&lPrice Type'
      Lore:
        - '#fffc9a▪ #ddeceeCurrent: #fffc9a%product_price_type%'
        - ''
        - '#ddeceeDepends on a price type, this menu'
        - '#ddeceewill have different settings.'
        - ''
        - '#ff9a9a[!]#ddecee Previous settings will be #ff9a9alost#ddecee!'
        - '#ff9a9a[!]#ddecee Make sure you have #ff9a9apermission#ddecee to do that.'
        - ''
        - '#9af7ff&lActions:'
        - '#9af7ff▪ #ddeceeLeft-Click: #9af7ffToggle'

  PRODUCT_CHANGE_PRICE_BUY:
    Priority: 5
    Slots: 10
    Type: PRODUCT_CHANGE_PRICE_BUY
    Item:
      Material: PLAYER_HEAD
      Head_Texture: 'eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvYmY2Yjg1ZjYyNjQ0NGRiZDViZGRmN2E1MjFmZTUyNzQ4ZmU0MzU2NGUwM2ZiZDM1YjZiNWU3OTdkZTk0MmQifX19'
      Name: '#fffc9a&lBuy Price'
      Lore:
        - '%price_buy%'

  PRODUCT_CHANGE_PRICE_SELL:
    Priority: 5
    Slots: 11
    Type: PRODUCT_CHANGE_PRICE_SELL
    Item:
      Material: PLAYER_HEAD
      Head_Texture: 'eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvYTlkYmVkNTIyZThkZTFhNjgxZGRkZDM3ODU0ZWU0MjY3ZWZjNDhiNTk5MTdmOWE5YWNiNDIwZDZmZGI5In19fQ=='
      Name: '#fffc9a&lSell Price'
      Lore:
        - '%price_sell%'

  PRODUCT_CHANGE_PRICE_FLOAT_REFRESH:
    Priority: 5
    Slots: 15
    Type: PRODUCT_CHANGE_PRICE_REFRESH
    Item:
      Material: PLAYER_HEAD
      Head_Texture: 'eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZDJkOTkzNDJiZTY3MTU2Y2VmNDhiNTBhOTcxOTI5ODkyMjJkNTY5YjQ0NjA5Mjg5OWNjMjMzNDc1NDJlNzFhYSJ9fX0='
      Name: '#fffc9a&lRefresh Settings'
      Lore:
        - '#fffc9a▪ #ddeceeRound Decimals: #fffc9a%product_pricer_float_round_decimals%'
        - '#fffc9a▪ #ddeceeDays: #fffc9a%product_pricer_float_refresh_days%'
        - '#fffc9a▪ #ddeceeTimes:'
        - '#fffc9a%product_pricer_float_refresh_times%'
        - ''
        - '#ddeceeSets, when the product price'
        - '#ddeceewill be refreshed. Until that, the'
        - '#ddeceeprevious generated price will be used.'
        - ''
        - '#ff9a9a&lNOTE:'
        - '#ddeceeYou have to provide at least #ff9a9aONE'
        - '#ddeceeday and time for the'
        - '#ddeceefloat price feature to work.'
        - ''
        - '#9af7ff&lActions:'
        - '#9af7ff▪ #ddecee[Q/Drop Key]: #9af7ffToggle Decimals'
        - '#9af7ff▪ #ddeceeLeft-Click: #9af7ffAdd Day'
        - '#9af7ff▪ #ddeceeShift-Left: #9af7ffClear Days'
        - '#9af7ff▪ #ddeceeRight-Click: #9af7ffAdd Time'
        - '#9af7ff▪ #ddeceeShift-Right: #9af7ffClear Times'

  PRODUCT_CHANGE_PRICE_DYNAMIC_INITIAL:
    Priority: 5
    Slots: 15
    Type: PRODUCT_CHANGE_PRICE_INITIAL
    Item:
      Material: PLAYER_HEAD
      Head_Texture: 'eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvODI0Zjc2OWM5NDUwZjIyZTQ4NGUwODljYTAyZTMyNGZlMzdiMThmNGMxOGVmMjk2MDIxODcxYmE0YWQwYzM5NiJ9fX0='
      Name: '#fffc9a&lInitial Price'
      Lore:
        - '#fffc9a▪ #ddeceeBuy: #fffc9a%product_pricer_dynamic_initial_buy%'
        - '#fffc9a▪ #ddeceeSell: #fffc9a%product_pricer_dynamic_initial_sell%'
        - ''
        - '#ddeceeSets initial price for the product.'
        - '#ddeceeThese values will be used as #fffc9adefault'
        - '#ddeceeones, and to calculate #fffc9afurther#ddecee price.'
        - ''
        - '#9af7ff&lActions:'
        - '#9af7ff▪ #ddeceeLeft-Click: #9af7ffChange Buy'
        - '#9af7ff▪ #ddeceeRight-Click: #9af7ffChange Sell'

  PRODUCT_CHANGE_PRICE_DYNAMIC_STEP:
    Priority: 5
    Slots: 16
    Type: PRODUCT_CHANGE_PRICE_STEP
    Item:
      Material: PLAYER_HEAD
      Head_Texture: 'eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvM2U0ZjJmOTY5OGMzZjE4NmZlNDRjYzYzZDJmM2M0ZjlhMjQxMjIzYWNmMDU4MTc3NWQ5Y2VjZDcwNzUifX19'
      Name: '#fffc9a&lPrice Step'
      Lore:
        - '#fffc9a▪ #ddeceeBuy: #fffc9a%product_pricer_dynamic_step_buy%'
        - '#fffc9a▪ #ddeceeSell: #fffc9a%product_pricer_dynamic_step_sell%'
        - ''
        - '#ddeceePrice will be #a5ff9aincreased#ddecee by #a5ff9a%product_pricer_dynamic_step_buy%#ddecee on each'
        - '#ddeceepurchase and #ff9a9adecreased#ddecee by #ff9a9a%product_pricer_dynamic_step_sell%'
        - '#ddeceeon each sale.'
        - ''
        - '#9af7ff&lActions:'
        - '#9af7ff▪ #ddeceeLeft-Click: #9af7ffChange Buy'
        - '#9af7ff▪ #ddeceeRight-Click: #9af7ffChange Sell'