Settings:
  Title: '&lShop Settings'
  Size: 9
  Inventory_Type: CHEST
  Auto_Refresh: 0

Content:
  SHOP_CHANGE_NAME:
    Item:
      Material: PLAYER_HEAD
      Head_Texture: eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZjVhMTlhZjBlNjFjYTQyNTMyYzA1OTlmYTBhMzkxNzUzZGY2YjcxZjlmYTRhMTc3ZjFhYTliMWQ4MWZlNmVlMiJ9fX0=
      Name: '#ffeea2&lShop Name'
      Lore:
        - '#ffeea2✔ #ddeceeCurrent: #ffeea2%shop_name%'
        - ''
        - '#ddeceeShop name to be displayed in'
        - '#ddeceeGUI and showcase.'
        - ''
        - '#ffeea2[▶] #ddeceeClick to #ffeea2change#ddecee.'
    Type: SHOP_CHANGE_NAME
    Slots: 0
    Priority: 5

  SHOP_CHANGE_TRANSACTIONS:
    Item:
      Material: PLAYER_HEAD
      Head_Texture: eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMTgzOTg0ODU1M2NhYmVkOTc3ZThkNWNjOTc2ZDQ0Y2JhMmVhYWVmZTFkYTQ0NjE4N2U4NTJlZGVlMTZiODcwZSJ9fX0=
      Name: '#ffeea2&lTrade Mode'
      Lore:
        - '#ffeea2✔ #ddeceeBuying: #ffeea2%shop_buy_allowed%'
        - '#ffeea2✔ #ddeceeSelling: #ffeea2%shop_sell_allowed%'
        - ''
        - '#ddeceeEnable/disable certain operations in the shop.'
        - ''
        - '#ffeea2[▶] #ddeceeLeft-click to toggle #ffeea2buying#ddecee.'
        - '#ffeea2[▶] #ddeceeRight-click to toggle #ffeea2selling#ddecee.'
    Type: SHOP_CHANGE_TRANSACTIONS
    Slots: 1
    Priority: 5

  SHOP_CHANGE_PRODUCTS:
    Item:
      Material: PLAYER_HEAD
      Head_Texture: eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvOTAwZDI4ZmY3YjU0M2RkMDg4ZDAwNGIxYjFmOTViMzhkNDQ0ZWEwNDYxZmY1YWUzYzY4ZDc2YzBjMTZlMjUyNyJ9fX0=
      Name: '#ffeea2&lShop Products'
      Lore:
        - '#ddeceeHere you can #ffeea2create#ddecee and #ffeea2manage'
        - '#ddeceeproducts of your shop.'
        - ''
        - '#ffeea2[▶] #ddeceeClick to #ffeea2navigate#ddecee.'
    Type: SHOP_CHANGE_PRODUCTS
    Slots: 2
    Priority: 5

  SHOP_BANK:
    Item:
      Material: PLAYER_HEAD
      Head_Texture: eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvYjg4OWNmY2JhY2JlNTk4ZThhMWNkODYxMGI0OWZjYjYyNjQ0ZThjYmE5ZDQ5MTFkMTIxMTM0NTA2ZDhlYTFiNyJ9fX0=
      Name: '#ffeea2&lShop Bank #ddecee(Global)'
      Lore:
        - '#ffeea2▪ #ddeceeBalance: #ffeea2%shop_bank_balance%'
        - ''
        - '#ddeceeBank is used to store shop''s funds.'
        - '#ddeceeIt''s global for all your shops.'
        - '#ddeceeBank #a5ff9agains#ddecee funds on sales,'
        - '#ddeceeand #ff9a9aspends#ddecee them on purchases.'
        - ''
        - '#ffeea2[▶] #ddeceeClick to #ffeea2navigate#ddecee.'
    Type: SHOP_BANK
    Slots: 3
    Priority: 5

  SHOP_CHANGE_TYPE:
    Item:
      Material: PLAYER_HEAD
      Head_Texture: eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvM2M1ZjNjM2Q1ZDdiMWNlMGYzMjA0MGMxNDU0ZGFmODg3OGUxY2MyOTllMDI1YmFkMmU2OTE5ZWJhZTIxZmJiOCJ9fX0=
      Name: '#ffeea2&lShop Type'
      Lore:
        - '#ffeea2✔ #ddeceeCurrent: #ffeea2%shop_type%'
        - ''
        - '#ddeceeSetting shop as #ffeea2admin shop#ddecee will'
        - '#ddeceemake it to have unlimited funds and items.'
        - ''
        - '#ff9a9a[❗]#ddecee Make sure you have #ff9a9apermission#ddecee to use it.'
        - ''
        - '#ffeea2[▶] #ddeceeClick to #ffeea2change#ddecee.'
    Type: SHOP_CHANGE_TYPE
    Slots: 6
    Priority: 5

  SHOP_DELETE:
    Item:
      Material: PLAYER_HEAD
      Head_Texture: eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvYjQ2NWY4MGJmMDJiNDA4ODg1OTg3YjAwOTU3Y2E1ZTllYjg3NGMzZmE4ODMwNTA5OTU5N2EzMzNhMzM2ZWUxNSJ9fX0=
      Name: '#ff9a9a&lDelete Shop'
      Lore:
        - '#ddeceePermanently deletes the shop.'
        - ''
        - '#ff9a9a[❗]#ddecee Remove all items first!'
        - ''
        - '#ffeea2[▶] #ddeceeSneak + Right-Click to #ffeea2delete#ddecee.'
    Type: SHOP_DELETE
    Slots: 8
    Priority: 5