Name: '&x&f&d&d&3&4&5&lF&x&f&c&d&3&4&9&la&x&f&c&d&4&4&d&lr&x&f&c&d&5&5&1&lm&x&f&c&d&6&5&5&le&x&f&c&d&7&5&9&lr&x&f&c&d&8&5&d&ls&x&f&c&d&9&6&2&l &x&f&c&d&9&6&6&lM&x&f&c&d&a&6&a&la&x&f&c&d&b&6&e&lr&x&f&c&d&c&7&2&lk&x&f&c&d&d&7&6&le&x&f&c&d&e&7&a&lt'
Description:
- '&x&d&4&d&9&d&8Everything your garden need.'
Pages: 2
Permission_Required: false
Citizens:
  Attached_NPC: ''
Transaction_Allowed:
  BUY: true
  SELL: true
Icon:
  Material: WHEAT
