Name: '<gradient:#fae409>&lArmory</gradient:#fbf18f>'
Pages: 2
Permission_Required: false
Transaction_Allowed:
  SELL: true
  BUY: true
Citizens:
  Attached_NPC: ''
Description:
- '#d4d9d8All type armors and weapons.'
Icon:
  Material: GOLDEN_SWORD
