Name: '<gradient:#7afd2f>&lWool Market</gradient:#b9f099>'
Pages: 1
Permission_Required: false
Transaction_Allowed:
  SELL: true
  BUY: true
Citizens:
  Attached_NPC: ''
Description:
- '#d4d9d8Wool with colors.'
Icon:
  Material: LIME_WOOL
