List:
  151a92f1-dad5-463a-9e58-452cb6e7ea8d:
    Shop_View:
      Slot: 19
      Page: 1
    Discount:
      Allowed: true
    Reward: {}
    Currency: vault
    Item_Meta_Enabled: true
    Price:
      Type: FLAT
      BUY: 50.0
      SELL: 20.0
    Stock:
      GLOBAL:
        BUY:
          Initial_Amount: -1
          Restock_Time: 0
        SELL:
          Initial_Amount: -1
          Restock_Time: 0
      PLAYER:
        BUY:
          Initial_Amount: -1
          Restock_Time: 0
        SELL:
          Initial_Amount: -1
          Restock_Time: 0
    Content:
      Commands: []
      Item: 5000080016ip002dmmirj5cdp62pjk79jn4obpbtrmurrc0400agrfeln78080
      Preview: 5000080016ip002dmmirj5cdp62pjk79jn4obpbtrmurrc0400agrfeln78080
  cb289548-1102-400d-86df-fc5809410e27:
    Shop_View:
      Slot: 10
      Page: 1
    Discount:
      Allowed: true
    Reward: {}
    Currency: vault
    Item_Meta_Enabled: true
    Price:
      Type: FLAT
      BUY: 50.0
      SELL: 20.0
    Stock:
      GLOBAL:
        BUY:
          Initial_Amount: -1
          Restock_Time: 0
        SELL:
          Initial_Amount: -1
          Restock_Time: 0
      PLAYER:
        BUY:
          Initial_Amount: -1
          Restock_Time: 0
        SELL:
          Initial_Amount: -1
          Restock_Time: 0
    Content:
      Commands: []
      Item: 1800020009km800kdlkmspb3e9gmct1qetk6it35btrmurrc0400agrfeln78080
      Preview: 1800020009km800kdlkmspb3e9gmct1qetk6it35btrmurrc0400agrfeln78080
  b72804a2-9f59-4a7e-a8c2-a5109c8bf8dd:
    Shop_View:
      Slot: 15
      Page: 1
    Discount:
      Allowed: true
    Reward: {}
    Currency: vault
    Item_Meta_Enabled: true
    Price:
      Type: FLAT
      BUY: 50.0
      SELL: 20.0
    Stock:
      GLOBAL:
        BUY:
          Initial_Amount: -1
          Restock_Time: 0
        SELL:
          Initial_Amount: -1
          Restock_Time: 0
      PLAYER:
        BUY:
          Initial_Amount: -1
          Restock_Time: 0
        SELL:
          Initial_Amount: -1
          Restock_Time: 0
    Content:
      Commands: []
      Item: 5000080016ip002dmmirj5cdp62pjk79m6irb5btrmurrc0400agrfeln78080
      Preview: 5000080016ip002dmmirj5cdp62pjk79m6irb5btrmurrc0400agrfeln78080
  14a23365-8a83-4bea-b5ee-ee2a0087edb0:
    Shop_View:
      Slot: 21
      Page: 1
    Discount:
      Allowed: true
    Reward: {}
    Currency: vault
    Item_Meta_Enabled: true
    Price:
      Type: FLAT
      BUY: 50.0
      SELL: 20.0
    Stock:
      GLOBAL:
        BUY:
          Initial_Amount: -1
          Restock_Time: 0
        SELL:
          Initial_Amount: -1
          Restock_Time: 0
      PLAYER:
        BUY:
          Initial_Amount: -1
          Restock_Time: 0
        SELL:
          Initial_Amount: -1
          Restock_Time: 0
    Content:
      Commands: []
      Item: 5000080016ip002dmmirj5cdp62pjk79hniobebtrmurrc0400agrfeln78080
      Preview: 5000080016ip002dmmirj5cdp62pjk79hniobebtrmurrc0400agrfeln78080
  e522aa83-8067-4685-b5ab-4b6e3867292b:
    Shop_View:
      Slot: 16
      Page: 1
    Discount:
      Allowed: true
    Reward: {}
    Currency: vault
    Item_Meta_Enabled: true
    Price:
      Type: FLAT
      BUY: 50.0
      SELL: 20.0
    Stock:
      GLOBAL:
        BUY:
          Initial_Amount: -1
          Restock_Time: 0
        SELL:
          Initial_Amount: -1
          Restock_Time: 0
      PLAYER:
        BUY:
          Initial_Amount: -1
          Restock_Time: 0
        SELL:
          Initial_Amount: -1
          Restock_Time: 0
    Content:
      Commands: []
      Item: 5000080016ip002dmmirj5cdp62pjk79o6irjbbtrmurrc0400agrfeln78080
      Preview: 5000080016ip002dmmirj5cdp62pjk79o6irjbbtrmurrc0400agrfeln78080
  fc274242-9fe1-4968-9520-087f75db548b:
    Shop_View:
      Slot: 32
      Page: 1
    Discount:
      Allowed: true
    Reward: {}
    Currency: vault
    Item_Meta_Enabled: true
    Price:
      Type: FLAT
      BUY: 50.0
      SELL: 20.0
    Stock:
      GLOBAL:
        BUY:
          Initial_Amount: -1
          Restock_Time: 0
        SELL:
          Initial_Amount: -1
          Restock_Time: 0
      PLAYER:
        BUY:
          Initial_Amount: -1
          Restock_Time: 0
        SELL:
          Initial_Amount: -1
          Restock_Time: 0
    Content:
      Commands: []
      Item: 1800020009km800kdlkmspb3e9gmct1qc9m62orbbtrmurrc0400agrfeln78080
      Preview: 1800020009km800kdlkmspb3e9gmct1qc9m62orbbtrmurrc0400agrfeln78080
  0b8f3a20-f5e7-42e6-8bd7-2b029233a03d:
    Shop_View:
      Slot: 23
      Page: 1
    Discount:
      Allowed: true
    Reward: {}
    Currency: vault
    Item_Meta_Enabled: true
    Price:
      Type: FLAT
      BUY: 50.0
      SELL: 20.0
    Stock:
      GLOBAL:
        BUY:
          Initial_Amount: -1
          Restock_Time: 0
        SELL:
          Initial_Amount: -1
          Restock_Time: 0
      PLAYER:
        BUY:
          Initial_Amount: -1
          Restock_Time: 0
        SELL:
          Initial_Amount: -1
          Restock_Time: 0
    Content:
      Commands: []
      Item: 5000080016ip002dmmirj5cdp62pjk79h6otb5btrmurrc0400agrfeln78080
      Preview: 5000080016ip002dmmirj5cdp62pjk79h6otb5btrmurrc0400agrfeln78080
  e2cfc181-3e42-4013-a899-13b785db22d3:
    Shop_View:
      Slot: 20
      Page: 1
    Discount:
      Allowed: true
    Reward: {}
    Currency: vault
    Item_Meta_Enabled: true
    Price:
      Type: FLAT
      BUY: 50.0
      SELL: 20.0
    Stock:
      GLOBAL:
        BUY:
          Initial_Amount: -1
          Restock_Time: 0
        SELL:
          Initial_Amount: -1
          Restock_Time: 0
      PLAYER:
        BUY:
          Initial_Amount: -1
          Restock_Time: 0
        SELL:
          Initial_Amount: -1
          Restock_Time: 0
    Content:
      Commands: []
      Item: 1800020009km800pdlkmspb3e9gmct1qdhkmeq3kbtjn4obpbtrmurrc0400agrfeln78080
      Preview: 1800020009km800pdlkmspb3e9gmct1qdhkmeq3kbtjn4obpbtrmurrc0400agrfeln78080
  1b9c563a-3f2e-4352-a2b3-44f441fe07a3:
    Shop_View:
      Slot: 24
      Page: 1
    Discount:
      Allowed: true
    Reward: {}
    Currency: vault
    Item_Meta_Enabled: true
    Price:
      Type: FLAT
      BUY: 50.0
      SELL: 20.0
    Stock:
      GLOBAL:
        BUY:
          Initial_Amount: -1
          Restock_Time: 0
        SELL:
          Initial_Amount: -1
          Restock_Time: 0
      PLAYER:
        BUY:
          Initial_Amount: -1
          Restock_Time: 0
        SELL:
          Initial_Amount: -1
          Restock_Time: 0
    Content:
      Commands: []
      Item: 1800020009km800kdlkmspb3e9gmct1qc9p6utrebtrmurrc0400agrfeln78080
      Preview: 1800020009km800kdlkmspb3e9gmct1qc9p6utrebtrmurrc0400agrfeln78080
  6a63aab1-4ec4-4078-b675-675f702cf70f:
    Shop_View:
      Slot: 12
      Page: 1
    Discount:
      Allowed: true
    Reward: {}
    Currency: vault
    Item_Meta_Enabled: true
    Price:
      Type: FLAT
      BUY: 50.0
      SELL: 20.0
    Stock:
      GLOBAL:
        BUY:
          Initial_Amount: -1
          Restock_Time: 0
        SELL:
          Initial_Amount: -1
          Restock_Time: 0
      PLAYER:
        BUY:
          Initial_Amount: -1
          Restock_Time: 0
        SELL:
          Initial_Amount: -1
          Restock_Time: 0
    Content:
      Commands: []
      Item: 2g0004000j9cg01crb9dpim6sj1cpq3krb1ctimst31btrmurrc0400agrfeln78080
      Preview: 2g0004000j9cg01crb9dpim6sj1cpq3krb1ctimst31btrmurrc0400agrfeln78080
  0c07ffc4-dcb4-4b6a-be3d-3669d143def4:
    Shop_View:
      Slot: 25
      Page: 1
    Discount:
      Allowed: true
    Reward: {}
    Currency: vault
    Item_Meta_Enabled: true
    Price:
      Type: FLAT
      BUY: 50.0
      SELL: 20.0
    Stock:
      GLOBAL:
        BUY:
          Initial_Amount: -1
          Restock_Time: 0
        SELL:
          Initial_Amount: -1
          Restock_Time: 0
      PLAYER:
        BUY:
          Initial_Amount: -1
          Restock_Time: 0
        SELL:
          Initial_Amount: -1
          Restock_Time: 0
    Content:
      Commands: []
      Item: 1800020009km800kdlkmspb3e9gmct1qctp6apbebtrmurrc0400agrfeln78080
      Preview: 1800020009km800kdlkmspb3e9gmct1qctp6apbebtrmurrc0400agrfeln78080
  a6a8b569-4e04-4b7e-b505-2b351d517bed:
    Shop_View:
      Slot: 22
      Page: 1
    Discount:
      Allowed: true
    Reward: {}
    Currency: vault
    Item_Meta_Enabled: true
    Price:
      Type: FLAT
      BUY: 50.0
      SELL: 20.0
    Stock:
      GLOBAL:
        BUY:
          Initial_Amount: -1
          Restock_Time: 0
        SELL:
          Initial_Amount: -1
          Restock_Time: 0
      PLAYER:
        BUY:
          Initial_Amount: -1
          Restock_Time: 0
        SELL:
          Initial_Amount: -1
          Restock_Time: 0
    Content:
      Commands: []
      Item: a0000g002d5i005bdd5n6aoric5j78ejgelp70r35btrmurrc0400agrfeln78080
      Preview: a0000g002d5i005bdd5n6aoric5j78ejgelp70r35btrmurrc0400agrfeln78080
  92f05f55-8e63-4b37-8553-6a53c60d5c83:
    Shop_View:
      Slot: 14
      Page: 1
    Discount:
      Allowed: true
    Reward: {}
    Currency: vault
    Item_Meta_Enabled: true
    Price:
      Type: FLAT
      BUY: 50.0
      SELL: 20.0
    Stock:
      GLOBAL:
        BUY:
          Initial_Amount: -1
          Restock_Time: 0
        SELL:
          Initial_Amount: -1
          Restock_Time: 0
      PLAYER:
        BUY:
          Initial_Amount: -1
          Restock_Time: 0
        SELL:
          Initial_Amount: -1
          Restock_Time: 0
    Content:
      Commands: []
      Item: a0000g002d5i005bdd5n6aoric5j78ejpclm6orrnbtrmurrc0400agrfeln78080
      Preview: a0000g002d5i005bdd5n6aoric5j78ejpclm6orrnbtrmurrc0400agrfeln78080
  652d5926-91e9-4d44-af5e-86ef79e93560:
    Shop_View:
      Slot: 11
      Page: 1
    Discount:
      Allowed: true
    Reward: {}
    Currency: vault
    Item_Meta_Enabled: true
    Price:
      Type: FLAT
      BUY: 50.0
      SELL: 20.0
    Stock:
      GLOBAL:
        BUY:
          Initial_Amount: -1
          Restock_Time: 0
        SELL:
          Initial_Amount: -1
          Restock_Time: 0
      PLAYER:
        BUY:
          Initial_Amount: -1
          Restock_Time: 0
        SELL:
          Initial_Amount: -1
          Restock_Time: 0
    Content:
      Commands: []
      Item: a0000g002d5i005bdd5n6aoric5j78ejfe9gmspr5btrmurrc0400agrfeln78080
      Preview: a0000g002d5i005bdd5n6aoric5j78ejfe9gmspr5btrmurrc0400agrfeln78080
  d00d14e2-f457-46b5-aeca-b59a04659160:
    Shop_View:
      Slot: 30
      Page: 1
    Discount:
      Allowed: true
    Reward: {}
    Currency: vault
    Item_Meta_Enabled: true
    Price:
      Type: FLAT
      BUY: 50.0
      SELL: 20.0
    Stock:
      GLOBAL:
        BUY:
          Initial_Amount: -1
          Restock_Time: 0
        SELL:
          Initial_Amount: -1
          Restock_Time: 0
      PLAYER:
        BUY:
          Initial_Amount: -1
          Restock_Time: 0
        SELL:
          Initial_Amount: -1
          Restock_Time: 0
    Content:
      Commands: []
      Item: k00010004qb40096qqbeclhn4ob6egt74pb4btrmurrc0400agrfeln78080
      Preview: k00010004qb40096qqbeclhn4ob6egt74pb4btrmurrc0400agrfeln78080
  082f478b-a73c-4960-a006-0640f11969da:
    Shop_View:
      Slot: 13
      Page: 1
    Discount:
      Allowed: true
    Reward: {}
    Currency: vault
    Item_Meta_Enabled: true
    Price:
      Type: FLAT
      BUY: 50.0
      SELL: 20.0
    Stock:
      GLOBAL:
        BUY:
          Initial_Amount: -1
          Restock_Time: 0
        SELL:
          Initial_Amount: -1
          Restock_Time: 0
      PLAYER:
        BUY:
          Initial_Amount: -1
          Restock_Time: 0
        SELL:
          Initial_Amount: -1
          Restock_Time: 0
    Content:
      Commands: []
      Item: 1800020009km800pdlkmspb3e9gmct1qdhkmeq3kbth6otb5btrmurrc0400agrfeln78080
      Preview: 1800020009km800pdlkmspb3e9gmct1qdhkmeq3kbth6otb5btrmurrc0400agrfeln78080
