Name: '&x&f&c&a&a&4&2&lF&x&f&c&a&c&4&7&li&x&f&c&a&e&4&c&ls&x&f&c&b&1&5&1&lh&x&f&c&b&3&5&6&l &x&f&c&b&5&5&b&lM&x&f&d&b&8&6&0&la&x&f&d&b&a&6&5&lr&x&f&d&b&c&6&a&lk&x&f&d&b&f&6&f&le&x&f&d&c&1&7&4&lt'
Description:
- '&x&d&4&d&9&d&8Evrything you can obtain'
- '&x&d&4&d&9&d&8when fishing.'
Pages: 1
Permission_Required: false
Citizens:
  Attached_NPC: ''
Transaction_Allowed:
  BUY: true
  SELL: true
Icon:
  Material: TROPICAL_FISH
