Name: '<gradient:#b88f44>&lBlock Market</gradient:#b79d6d>'
Pages: 4
Permission_Required: false
Transaction_Allowed:
  SELL: true
  BUY: true
Citizens:
  Attached_NPC: ''
Description:
- '#d4d9d8Building blocks and resources.'
Icon:
  Material: JUNGLE_LOG
