Name: '&x&c&4&3&a&1&b&lF&x&c&4&3&e&2&0&lo&x&c&4&4&2&2&5&lo&x&c&4&4&6&2&a&ld&x&c&4&4&a&2&f&l &x&c&4&4&e&3&4&lM&x&c&5&5&2&3&9&la&x&c&5&5&6&3&e&lr&x&c&5&5&a&4&3&lk&x&c&5&5&e&4&8&le&x&c&5&6&2&4&d&lt'
Pages: 1
Permission_Required: false
Transaction_Allowed:
  SELL: true
  BUY: true
Citizens:
  Attached_NPC: ''
Description:
- '&x&d&4&d&9&d&8All regular food.'
Icon:
  Material: SWEET_BERRIES
