List:
  e13bd3b0-3c3f-42c6-a2c3-8bdc116fd54a:
    Shop_View:
      Slot: 0
      Page: 1
    Discount:
      Allowed: true
    Item_Meta_Enabled: true
    Stock:
      GLOBAL:
        BUY:
          Initial_Amount: -1
          Restock_Time: 0
        SELL:
          Initial_Amount: -1
          Restock_Time: 0
      PLAYER:
        BUY:
          Initial_Amount: -1
          Restock_Time: 0
        SELL:
          Initial_Amount: -1
          Restock_Time: 0
    Currency: vault
    Price:
      Type: FLAT
      BUY: 50.0
      SELL: 20.0
    Reward: {}
    Content:
      Commands: []
      Item: 1800020009km800fdlkmspb3e9gmct1qc5o70r350400agrfeln78080
      Preview: 1800020009km800fdlkmspb3e9gmct1qc5o70r350400agrfeln78080
  a1bc3225-58be-4daf-b035-612468937363:
    Shop_View:
      Slot: 1
      Page: 1
    Discount:
      Allowed: true
    Item_Meta_Enabled: true
    Stock:
      GLOBAL:
        BUY:
          Initial_Amount: -1
          Restock_Time: 0
        SELL:
          Initial_Amount: -1
          Restock_Time: 0
      PLAYER:
        BUY:
          Initial_Amount: -1
          Restock_Time: 0
        SELL:
          Initial_Amount: -1
          Restock_Time: 0
    Currency: vault
    Price:
      Type: FLAT
      BUY: 1000.0
      SELL: 500.0
    Reward: {}
    Content:
      Commands: []
      Item: 2g0004000j9cg01crb9dpim6sj1cpq3kprfdhi6arivc5o70r350400agrfeln78080
      Preview: 2g0004000j9cg01crb9dpim6sj1cpq3kprfdhi6arivc5o70r350400agrfeln78080
  57d13b83-0f22-496f-a62b-f24e81203d31:
    Shop_View:
      Slot: 2
      Page: 1
    Discount:
      Allowed: false
    Item_Meta_Enabled: false
    Stock:
      GLOBAL:
        BUY:
          Initial_Amount: -1
          Restock_Time: 0
        SELL:
          Initial_Amount: -1
          Restock_Time: 0
      PLAYER:
        BUY:
          Initial_Amount: -1
          Restock_Time: 0
        SELL:
          Initial_Amount: -1
          Restock_Time: 0
    Currency: vault
    Price:
      Type: FLAT
      BUY: 50000.0
      SELL: 25000.0
    Reward: {}
    Content:
      Commands: []
      Item: 2g0004000j9cg020rb9dpim6sj1cpq3kpbecdk62rjkcli5uprfdhi6arivc5o70r350400agrfeln78080
      Preview: 2g0004000j9cg020rb9dpim6sj1cpq3kpbecdk62rjkcli5uprfdhi6arivc5o70r350400agrfeln78080
  dad3b1ac-807b-4ba3-a38e-cc476a1a6f5d:
    Shop_View:
      Slot: 7
      Page: 1
    Discount:
      Allowed: true
    Item_Meta_Enabled: true
    Stock:
      GLOBAL:
        BUY:
          Initial_Amount: -1
          Restock_Time: 0
        SELL:
          Initial_Amount: -1
          Restock_Time: 0
      PLAYER:
        BUY:
          Initial_Amount: -1
          Restock_Time: 0
        SELL:
          Initial_Amount: -1
          Restock_Time: 0
    Currency: vault
    Price:
      Type: FLAT
      BUY: 50.0
      SELL: 20.0
    Reward: {}
    Content:
      Commands: []
      Item: 1800020009km800fdlkmspb3e9gmct1qc9p6aob40400agrfeln78080
      Preview: 1800020009km800fdlkmspb3e9gmct1qc9p6aob40400agrfeln78080
  cf693cd4-46cd-484e-a740-fa9b69a4e6b0:
    Shop_View:
      Slot: 8
      Page: 1
    Discount:
      Allowed: true
    Item_Meta_Enabled: true
    Stock:
      GLOBAL:
        BUY:
          Initial_Amount: -1
          Restock_Time: 0
        SELL:
          Initial_Amount: -1
          Restock_Time: 0
      PLAYER:
        BUY:
          Initial_Amount: -1
          Restock_Time: 0
        SELL:
          Initial_Amount: -1
          Restock_Time: 0
    Currency: vault
    Price:
      Type: FLAT
      BUY: 500.0
      SELL: 250.0
    Reward: {}
    Content:
      Commands: []
      Item: a0000g002d5i005bdd5n6aoric5j78ejic5h64qbkbtpn8pbn0400agrfeln78080
      Preview: a0000g002d5i005bdd5n6aoric5j78ejic5h64qbkbtpn8pbn0400agrfeln78080
  ee162a76-2dd6-418a-bafa-eb35bad67f92:
    Shop_View:
      Slot: 9
      Page: 1
    Discount:
      Allowed: true
    Item_Meta_Enabled: true
    Stock:
      GLOBAL:
        BUY:
          Initial_Amount: -1
          Restock_Time: 0
        SELL:
          Initial_Amount: -1
          Restock_Time: 0
      PLAYER:
        BUY:
          Initial_Amount: -1
          Restock_Time: 0
        SELL:
          Initial_Amount: -1
          Restock_Time: 0
    Currency: vault
    Price:
      Type: FLAT
      BUY: 50.0
      SELL: 20.0
    Reward: {}
    Content:
      Commands: []
      Item: a0000g002d5i0043dd5n6aoric5j78ej3dtnmmqb50400agrfeln78080
      Preview: a0000g002d5i0043dd5n6aoric5j78ej3dtnmmqb50400agrfeln78080
  96b478e6-9c08-42ca-bdcd-1311cc3e5bfb:
    Shop_View:
      Slot: 10
      Page: 1
    Discount:
      Allowed: true
    Item_Meta_Enabled: true
    Stock:
      GLOBAL:
        BUY:
          Initial_Amount: -1
          Restock_Time: 0
        SELL:
          Initial_Amount: -1
          Restock_Time: 0
      PLAYER:
        BUY:
          Initial_Amount: -1
          Restock_Time: 0
        SELL:
          Initial_Amount: -1
          Restock_Time: 0
    Currency: vault
    Price:
      Type: FLAT
      BUY: 50.0
      SELL: 20.0
    Reward: {}
    Content:
      Commands: []
      Item: a0000g002d5i005bdd5n6aoric5j78ejgelmn0qr9dpfn0qb50400agrfeln78080
      Preview: a0000g002d5i005bdd5n6aoric5j78ejgelmn0qr9dpfn0qb50400agrfeln78080
  2271e4d6-5b8d-4276-b8d4-ae56a0fb9f89:
    Shop_View:
      Slot: 11
      Page: 1
    Discount:
      Allowed: true
    Item_Meta_Enabled: true
    Stock:
      GLOBAL:
        BUY:
          Initial_Amount: -1
          Restock_Time: 0
        SELL:
          Initial_Amount: -1
          Restock_Time: 0
      PLAYER:
        BUY:
          Initial_Amount: -1
          Restock_Time: 0
        SELL:
          Initial_Amount: -1
          Restock_Time: 0
    Currency: vault
    Price:
      Type: FLAT
      BUY: 50.0
      SELL: 20.0
    Reward: {}
    Content:
      Commands: []
      Item: 5000080016ip001pmmirj5cdp62pjk79hm2qr50400agrfeln78080
      Preview: 5000080016ip001pmmirj5cdp62pjk79hm2qr50400agrfeln78080
  74329ee2-6706-4f18-83f1-86badcc7821a:
    Shop_View:
      Slot: 17
      Page: 1
    Discount:
      Allowed: true
    Item_Meta_Enabled: true
    Stock:
      GLOBAL:
        BUY:
          Initial_Amount: -1
          Restock_Time: 0
        SELL:
          Initial_Amount: -1
          Restock_Time: 0
      PLAYER:
        BUY:
          Initial_Amount: -1
          Restock_Time: 0
        SELL:
          Initial_Amount: -1
          Restock_Time: 0
    Currency: vault
    Price:
      Type: FLAT
      BUY: 50.0
      SELL: 20.0
    Reward: {}
    Content:
      Commands: []
      Item: k00010004qb400bmqqbeclhn4ob6egt6qtbjd1p6urrdbtpn8pbn0400agrfeln78080
      Preview: k00010004qb400bmqqbeclhn4ob6egt6qtbjd1p6urrdbtpn8pbn0400agrfeln78080
  dbeb4c50-224f-4d9b-a4af-0263513c8997:
    Shop_View:
      Slot: 18
      Page: 1
    Discount:
      Allowed: true
    Item_Meta_Enabled: true
    Stock:
      GLOBAL:
        BUY:
          Initial_Amount: -1
          Restock_Time: 0
        SELL:
          Initial_Amount: -1
          Restock_Time: 0
      PLAYER:
        BUY:
          Initial_Amount: -1
          Restock_Time: 0
        SELL:
          Initial_Amount: -1
          Restock_Time: 0
    Currency: vault
    Price:
      Type: FLAT
      BUY: 50.0
      SELL: 20.0
    Reward: {}
    Content:
      Commands: []
      Item: a0000g002d5i005bdd5n6aoric5j78ejdclm6urivedm6ior50400agrfeln78080
      Preview: a0000g002d5i005bdd5n6aoric5j78ejdclm6urivedm6ior50400agrfeln78080
  c4d4b4bd-84a9-4096-a022-585244ec7bf6:
    Shop_View:
      Slot: 19
      Page: 1
    Discount:
      Allowed: true
    Item_Meta_Enabled: true
    Stock:
      GLOBAL:
        BUY:
          Initial_Amount: -1
          Restock_Time: 0
        SELL:
          Initial_Amount: -1
          Restock_Time: 0
      PLAYER:
        BUY:
          Initial_Amount: -1
          Restock_Time: 0
        SELL:
          Initial_Amount: -1
          Restock_Time: 0
    Currency: vault
    Price:
      Type: FLAT
      BUY: 50.0
      SELL: 20.0
    Reward: {}
    Content:
      Commands: []
      Item: a0000g002d5i0043dd5n6aoric5j78ej3c5p74rrk0400agrfeln78080
      Preview: a0000g002d5i0043dd5n6aoric5j78ej3c5p74rrk0400agrfeln78080
  6f7eb127-2783-4928-9fa8-0603b66c69b2:
    Shop_View:
      Slot: 20
      Page: 1
    Discount:
      Allowed: false
    Item_Meta_Enabled: false
    Stock:
      GLOBAL:
        BUY:
          Initial_Amount: -1
          Restock_Time: 0
        SELL:
          Initial_Amount: -1
          Restock_Time: 0
      PLAYER:
        BUY:
          Initial_Amount: -1
          Restock_Time: 0
        SELL:
          Initial_Amount: -1
          Restock_Time: 0
    Currency: vault
    Price:
      Type: FLAT
      BUY: 1000.0
      SELL: 500.0
    Reward: {}
    Content:
      Commands: []
      Item: k00010004qb400bmqqbeclhn4ob6egt6errcchimsnr3c5p74rrk0400agrfeln78080
      Preview: k00010004qb400bmqqbeclhn4ob6egt6errcchimsnr3c5p74rrk0400agrfeln78080
  6460c272-0c81-47e6-9190-367748d3fe8b:
    Shop_View:
      Slot: 21
      Page: 1
    Discount:
      Allowed: true
    Item_Meta_Enabled: true
    Stock:
      GLOBAL:
        BUY:
          Initial_Amount: -1
          Restock_Time: 0
        SELL:
          Initial_Amount: -1
          Restock_Time: 0
      PLAYER:
        BUY:
          Initial_Amount: -1
          Restock_Time: 0
        SELL:
          Initial_Amount: -1
          Restock_Time: 0
    Currency: vault
    Price:
      Type: FLAT
      BUY: 75.0
      SELL: 50.0
    Reward: {}
    Content:
      Commands: []
      Item: 2g0004000j9cg01crb9dpim6sj1cpq3koj1ddim8nrgdtq62t3f0400agrfeln78080
      Preview: 2g0004000j9cg01crb9dpim6sj1cpq3koj1ddim8nrgdtq62t3f0400agrfeln78080
  500be0bd-2229-47ee-b454-1f1c9b7ffef6:
    Shop_View:
      Slot: 26
      Page: 1
    Discount:
      Allowed: false
    Item_Meta_Enabled: false
    Stock:
      GLOBAL:
        BUY:
          Initial_Amount: -1
          Restock_Time: 0
        SELL:
          Initial_Amount: -1
          Restock_Time: 0
      PLAYER:
        BUY:
          Initial_Amount: -1
          Restock_Time: 0
        SELL:
          Initial_Amount: -1
          Restock_Time: 0
    Currency: vault
    Price:
      Type: FLAT
      BUY: 50.0
      SELL: 20.0
    Reward: {}
    Content:
      Commands: []
      Item: 5000080016ip001pmmirj5cdp62pjk79h6utrc0400agrfeln78080
      Preview: 5000080016ip001pmmirj5cdp62pjk79h6utrc0400agrfeln78080
  1911b494-c145-4dd4-ae2b-83fec37fbe7c:
    Shop_View:
      Slot: 27
      Page: 1
    Discount:
      Allowed: true
    Item_Meta_Enabled: true
    Stock:
      GLOBAL:
        BUY:
          Initial_Amount: -1
          Restock_Time: 0
        SELL:
          Initial_Amount: -1
          Restock_Time: 0
      PLAYER:
        BUY:
          Initial_Amount: -1
          Restock_Time: 0
        SELL:
          Initial_Amount: -1
          Restock_Time: 0
    Currency: vault
    Price:
      Type: FLAT
      BUY: 100.0
      SELL: 50.0
    Reward: {}
    Content:
      Commands: []
      Item: 1800020009km800pdlkmspb3e9gmct1qcdnmuqr5chfn0rriddhmgrrg0400agrfeln78080
      Preview: 1800020009km800pdlkmspb3e9gmct1qcdnmuqr5chfn0rriddhmgrrg0400agrfeln78080
  5a818f4e-6283-4361-bb67-530c418d429f:
    Shop_View:
      Slot: 28
      Page: 1
    Discount:
      Allowed: true
    Item_Meta_Enabled: true
    Stock:
      GLOBAL:
        BUY:
          Initial_Amount: -1
          Restock_Time: 0
        SELL:
          Initial_Amount: -1
          Restock_Time: 0
      PLAYER:
        BUY:
          Initial_Amount: -1
          Restock_Time: 0
        SELL:
          Initial_Amount: -1
          Restock_Time: 0
    Currency: vault
    Price:
      Type: FLAT
      BUY: 100.0
      SELL: 50.0
    Reward: {}
    Content:
      Commands: []
      Item: a0000g002d5i005bdd5n6aoric5j78ej3dtnmmpb4bth6apb60400agrfeln78080
      Preview: a0000g002d5i005bdd5n6aoric5j78ej3dtnmmpb4bth6apb60400agrfeln78080
  dd7ecf00-47f8-4d34-a7bb-3b2e026ec865:
    Shop_View:
      Slot: 29
      Page: 1
    Discount:
      Allowed: true
    Item_Meta_Enabled: true
    Stock:
      GLOBAL:
        BUY:
          Initial_Amount: -1
          Restock_Time: 0
        SELL:
          Initial_Amount: -1
          Restock_Time: 0
      PLAYER:
        BUY:
          Initial_Amount: -1
          Restock_Time: 0
        SELL:
          Initial_Amount: -1
          Restock_Time: 0
    Currency: vault
    Price:
      Type: FLAT
      BUY: 100.0
      SELL: 50.0
    Reward: {}
    Content:
      Commands: []
      Item: k00010004qb400bmqqbeclhn4ob6egt66rrfddim8nrdelq78rre0400agrfeln78080
      Preview: k00010004qb400bmqqbeclhn4ob6egt66rrfddim8nrdelq78rre0400agrfeln78080
  dcaf8676-0860-43f6-8c6b-2f8543120cb5:
    Shop_View:
      Slot: 30
      Page: 1
    Discount:
      Allowed: true
    Item_Meta_Enabled: true
    Stock:
      GLOBAL:
        BUY:
          Initial_Amount: -1
          Restock_Time: 0
        SELL:
          Initial_Amount: -1
          Restock_Time: 0
      PLAYER:
        BUY:
          Initial_Amount: -1
          Restock_Time: 0
        SELL:
          Initial_Amount: -1
          Restock_Time: 0
    Currency: vault
    Price:
      Type: FLAT
      BUY: 100.0
      SELL: 50.0
    Reward: {}
    Content:
      Commands: []
      Item: k00010004qb400bmqqbeclhn4ob6egt66rrfddim8nric5h64qbk0400agrfeln78080
      Preview: k00010004qb400bmqqbeclhn4ob6egt66rrfddim8nric5h64qbk0400agrfeln78080
  986ac974-106e-4835-857c-a861b3c66f44:
    Shop_View:
      Slot: 31
      Page: 1
    Discount:
      Allowed: true
    Item_Meta_Enabled: true
    Stock:
      GLOBAL:
        BUY:
          Initial_Amount: -1
          Restock_Time: 0
        SELL:
          Initial_Amount: -1
          Restock_Time: 0
      PLAYER:
        BUY:
          Initial_Amount: -1
          Restock_Time: 0
        SELL:
          Initial_Amount: -1
          Restock_Time: 0
    Currency: vault
    Price:
      Type: FLAT
      BUY: 100.0
      SELL: 50.0
    Reward: {}
    Content:
      Commands: []
      Item: 5000080016ip0031mmirj5cdp62pjk79hmurrbcli5uor8d5hmmpbe0400agrfeln78080
      Preview: 5000080016ip0031mmirj5cdp62pjk79hmurrbcli5uor8d5hmmpbe0400agrfeln78080
  bd93f5a1-4fdb-463c-88df-d6d264a2d0eb:
    Shop_View:
      Slot: 32
      Page: 1
    Discount:
      Allowed: true
    Item_Meta_Enabled: true
    Stock:
      GLOBAL:
        BUY:
          Initial_Amount: -1
          Restock_Time: 0
        SELL:
          Initial_Amount: -1
          Restock_Time: 0
      PLAYER:
        BUY:
          Initial_Amount: -1
          Restock_Time: 0
        SELL:
          Initial_Amount: -1
          Restock_Time: 0
    Currency: vault
    Price:
      Type: FLAT
      BUY: 100.0
      SELL: 50.0
    Reward: {}
    Content:
      Commands: []
      Item: k00010004qb400bmqqbeclhn4ob6egt66rrfddim8nrjc5m6qrre0400agrfeln78080
      Preview: k00010004qb400bmqqbeclhn4ob6egt66rrfddim8nrjc5m6qrre0400agrfeln78080
  94b381d8-8341-4ee3-82d8-484228df803c:
    Shop_View:
      Slot: 33
      Page: 1
    Discount:
      Allowed: true
    Item_Meta_Enabled: true
    Stock:
      GLOBAL:
        BUY:
          Initial_Amount: -1
          Restock_Time: 0
        SELL:
          Initial_Amount: -1
          Restock_Time: 0
      PLAYER:
        BUY:
          Initial_Amount: -1
          Restock_Time: 0
        SELL:
          Initial_Amount: -1
          Restock_Time: 0
    Currency: vault
    Price:
      Type: FLAT
      BUY: 100.0
      SELL: 50.0
    Reward: {}
    Content:
      Commands: []
      Item: 1800020009km800kdlkmspb3e9gmct1qcdnmuqr5chfm6rr40400agrfeln78080
      Preview: 1800020009km800kdlkmspb3e9gmct1qcdnmuqr5chfm6rr40400agrfeln78080
  8f2f838b-5c14-4938-9331-2a48971b4f9d:
    Shop_View:
      Slot: 36
      Page: 1
    Discount:
      Allowed: false
    Item_Meta_Enabled: false
    Stock:
      GLOBAL:
        BUY:
          Initial_Amount: -1
          Restock_Time: 0
        SELL:
          Initial_Amount: -1
          Restock_Time: 0
      PLAYER:
        BUY:
          Initial_Amount: -1
          Restock_Time: 0
        SELL:
          Initial_Amount: -1
          Restock_Time: 0
    Currency: vault
    Price:
      Type: FLAT
      BUY: 50.0
      SELL: 20.0
    Reward: {}
    Content:
      Commands: []
      Item: k00010004qb400bmqqbeclhn4ob6egt76tr5clq5uoj5e9p6ipbj0400agrfeln78080
      Preview: k00010004qb400bmqqbeclhn4ob6egt76tr5clq5uoj5e9p6ipbj0400agrfeln78080
  524709a2-5d06-4a79-ba2a-72158b14f096:
    Shop_View:
      Slot: 37
      Page: 1
    Discount:
      Allowed: false
    Item_Meta_Enabled: false
    Stock:
      GLOBAL:
        BUY:
          Initial_Amount: -1
          Restock_Time: 0
        SELL:
          Initial_Amount: -1
          Restock_Time: 0
      PLAYER:
        BUY:
          Initial_Amount: -1
          Restock_Time: 0
        SELL:
          Initial_Amount: -1
          Restock_Time: 0
    Currency: vault
    Price:
      Type: FLAT
      BUY: 50.0
      SELL: 20.0
    Reward: {}
    Content:
      Commands: []
      Item: 2g0004000j9cg01crb9dpim6sj1cpq3kprcdtrluoj5e9p6ipbj0400agrfeln78080
      Preview: 2g0004000j9cg01crb9dpim6sj1cpq3kprcdtrluoj5e9p6ipbj0400agrfeln78080
  0b1e9224-c7be-4375-8c36-dbdf44700608:
    Shop_View:
      Slot: 38
      Page: 1
    Discount:
      Allowed: false
    Item_Meta_Enabled: false
    Stock:
      GLOBAL:
        BUY:
          Initial_Amount: -1
          Restock_Time: 0
        SELL:
          Initial_Amount: -1
          Restock_Time: 0
      PLAYER:
        BUY:
          Initial_Amount: -1
          Restock_Time: 0
        SELL:
          Initial_Amount: -1
          Restock_Time: 0
    Currency: vault
    Price:
      Type: FLAT
      BUY: 50.0
      SELL: 20.0
    Reward: {}
    Content:
      Commands: []
      Item: 2g0004000j9cg01crb9dpim6sj1cpq3kor8dtp7asqvcpp7aqbk0400agrfeln78080
      Preview: 2g0004000j9cg01crb9dpim6sj1cpq3kor8dtp7asqvcpp7aqbk0400agrfeln78080
