Name: '<gradient:#409ed9>&lBrewing</gradient:#97d5fc>'
Pages: 1
Permission_Required: false
Transaction_Allowed:
  SELL: true
  BUY: true
Citizens:
  Attached_NPC: ''
Description:
- '#d4d9d8Potions and Ingredients.'
Icon:
  Material: POTION
  Color: '0,0,200'