Name: '<gradient:#75fce6>&lTool Store</gradient:#b4fdf1>'
Pages: 1
Permission_Required: false
Description:
- '#d4d9d8All type tools.'
Transaction_Allowed:
  SELL: true
  BUY: true
Citizens:
  Attached_NPC: ''
Icon:
  Material: DIAMOND_PICKAXE