List:
  69a3f183-e514-4827-b467-9909e79303f0:
    Shop_View:
      Slot: 25
      Page: 1
    Discount:
      Allowed: true
    Reward: {}
    Currency: vault
    Item_Meta_Enabled: true
    Price:
      Type: FLAT
      BUY: 50.0
      SELL: 20.0
    Stock:
      GLOBAL:
        BUY:
          Initial_Amount: -1
          Restock_Time: 0
        SELL:
          Initial_Amount: -1
          Restock_Time: 0
      PLAYER:
        BUY:
          Initial_Amount: -1
          Restock_Time: 0
        SELL:
          Initial_Amount: -1
          Restock_Time: 0
    Content:
      Commands: []
      Item: 1800020009km800pdlkmspb3e9gmct1qchkm2rbfdpi5us39cdlm2u3518006t31cs1g01i4c5mm2pr5000000000400agrfeln78080
      Preview: 1800020009km800pdlkmspb3e9gmct1qchkm2rbfdpi5us39cdlm2u3518006t31cs1g01i4c5mm2pr5000000000400agrfeln78080
  090b5090-e13f-46c3-a681-272d9aaf4b50:
    Shop_View:
      Slot: 32
      Page: 1
    Discount:
      Allowed: true
    Reward: {}
    Currency: vault
    Item_Meta_Enabled: true
    Price:
      Type: FLAT
      BUY: 50.0
      SELL: 20.0
    Stock:
      GLOBAL:
        BUY:
          Initial_Amount: -1
          Restock_Time: 0
        SELL:
          Initial_Amount: -1
          Restock_Time: 0
      PLAYER:
        BUY:
          Initial_Amount: -1
          Restock_Time: 0
        SELL:
          Initial_Amount: -1
          Restock_Time: 0
    Content:
      Commands: []
      Item: k00010004qb40096qqbeclhn4ob6egt6isjfdpfmgrr518006t31cs1g01i4c5mm2pr5000000000400agrfeln78080
      Preview: k00010004qb40096qqbeclhn4ob6egt6isjfdpfmgrr518006t31cs1g01i4c5mm2pr5000000000400agrfeln78080
  e783ddfb-3ea3-4e53-8fa6-25dc74d8bbbb:
    Shop_View:
      Slot: 23
      Page: 1
    Discount:
      Allowed: true
    Reward: {}
    Currency: vault
    Item_Meta_Enabled: true
    Price:
      Type: FLAT
      BUY: 50.0
      SELL: 20.0
    Stock:
      GLOBAL:
        BUY:
          Initial_Amount: -1
          Restock_Time: 0
        SELL:
          Initial_Amount: -1
          Restock_Time: 0
      PLAYER:
        BUY:
          Initial_Amount: -1
          Restock_Time: 0
        SELL:
          Initial_Amount: -1
          Restock_Time: 0
    Content:
      Commands: []
      Item: 2g0004000j9cg01crb9dpim6sj1cpq3kqbidtn5us39cdlm2u3518006t31cs1g01i4c5mm2pr5000000000400agrfeln78080
      Preview: 2g0004000j9cg01crb9dpim6sj1cpq3kqbidtn5us39cdlm2u3518006t31cs1g01i4c5mm2pr5000000000400agrfeln78080
  8cfec538-c4f4-4b87-9a6d-3d7324fac17f:
    Shop_View:
      Slot: 16
      Page: 1
    Discount:
      Allowed: true
    Reward: {}
    Currency: vault
    Item_Meta_Enabled: true
    Price:
      Type: FLAT
      BUY: 50.0
      SELL: 20.0
    Stock:
      GLOBAL:
        BUY:
          Initial_Amount: -1
          Restock_Time: 0
        SELL:
          Initial_Amount: -1
          Restock_Time: 0
      PLAYER:
        BUY:
          Initial_Amount: -1
          Restock_Time: 0
        SELL:
          Initial_Amount: -1
          Restock_Time: 0
    Content:
      Commands: []
      Item: 5000080016ip0031mmirj5cdp62pjk79i6iobddtn68nrjd1nncpbc18006t31cs1g01i4c5mm2pr5000000000400agrfeln78080
      Preview: 5000080016ip0031mmirj5cdp62pjk79i6iobddtn68nrjd1nncpbc18006t31cs1g01i4c5mm2pr5000000000400agrfeln78080
  71150b16-54db-4b81-a0c5-29f3d5ee846c:
    Shop_View:
      Slot: 3
      Page: 1
    Discount:
      Allowed: true
    Reward: {}
    Currency: vault
    Item_Meta_Enabled: true
    Price:
      Type: FLAT
      BUY: 50.0
      SELL: 20.0
    Stock:
      GLOBAL:
        BUY:
          Initial_Amount: -1
          Restock_Time: 0
        SELL:
          Initial_Amount: -1
          Restock_Time: 0
      PLAYER:
        BUY:
          Initial_Amount: -1
          Restock_Time: 0
        SELL:
          Initial_Amount: -1
          Restock_Time: 0
    Content:
      Commands: []
      Item: a0000g002d5i0043dd5n6aoric5j78ejjd1im2sjj18006t31cs1g01i4c5mm2pr5000000000400agrfeln78080
      Preview: a0000g002d5i0043dd5n6aoric5j78ejjd1im2sjj18006t31cs1g01i4c5mm2pr5000000000400agrfeln78080
  3f04d8f4-2555-4f5f-9131-32bb436cd3a5:
    Shop_View:
      Slot: 7
      Page: 1
    Discount:
      Allowed: true
    Reward: {}
    Currency: vault
    Item_Meta_Enabled: true
    Price:
      Type: FLAT
      BUY: 50.0
      SELL: 20.0
    Stock:
      GLOBAL:
        BUY:
          Initial_Amount: -1
          Restock_Time: 0
        SELL:
          Initial_Amount: -1
          Restock_Time: 0
      PLAYER:
        BUY:
          Initial_Amount: -1
          Restock_Time: 0
        SELL:
          Initial_Amount: -1
          Restock_Time: 0
    Content:
      Commands: []
      Item: 1800020009km800fdlkmspb3e9gmct1qcdm6uorb0400agrfeln78080
      Preview: 1800020009km800fdlkmspb3e9gmct1qcdm6uorb0400agrfeln78080
  69874a22-36c0-45a2-959d-60c991fcbcfe:
    Shop_View:
      Slot: 21
      Page: 1
    Discount:
      Allowed: true
    Reward: {}
    Currency: vault
    Item_Meta_Enabled: true
    Price:
      Type: FLAT
      BUY: 50.0
      SELL: 20.0
    Stock:
      GLOBAL:
        BUY:
          Initial_Amount: -1
          Restock_Time: 0
        SELL:
          Initial_Amount: -1
          Restock_Time: 0
      PLAYER:
        BUY:
          Initial_Amount: -1
          Restock_Time: 0
        SELL:
          Initial_Amount: -1
          Restock_Time: 0
    Content:
      Commands: []
      Item: k00010004qb400bmqqbeclhn4ob6egt76t3fdpilus39cdlm2u3518006t31cs1g01i4c5mm2pr5000000000400agrfeln78080
      Preview: k00010004qb400bmqqbeclhn4ob6egt76t3fdpilus39cdlm2u3518006t31cs1g01i4c5mm2pr5000000000400agrfeln78080
  f6851609-3f21-4f56-9266-bcfc8f84149a:
    Shop_View:
      Slot: 37
      Page: 1
    Discount:
      Allowed: true
    Reward: {}
    Currency: vault
    Item_Meta_Enabled: true
    Price:
      Type: FLAT
      BUY: 50.0
      SELL: 20.0
    Stock:
      GLOBAL:
        BUY:
          Initial_Amount: -1
          Restock_Time: 0
        SELL:
          Initial_Amount: -1
          Restock_Time: 0
      PLAYER:
        BUY:
          Initial_Amount: -1
          Restock_Time: 0
        SELL:
          Initial_Amount: -1
          Restock_Time: 0
    Content:
      Commands: []
      Item: 1800020009km800kdlkmspb3e9gmct1qetnmup35dpfm2u3518006t31cs1g01i4c5mm2pr5000000000400agrfeln78080
      Preview: 1800020009km800kdlkmspb3e9gmct1qetnmup35dpfm2u3518006t31cs1g01i4c5mm2pr5000000000400agrfeln78080
  5129ca16-ca67-4981-96df-f0527dea97c6:
    Shop_View:
      Slot: 30
      Page: 1
    Discount:
      Allowed: true
    Reward: {}
    Currency: vault
    Item_Meta_Enabled: true
    Price:
      Type: FLAT
      BUY: 50.0
      SELL: 20.0
    Stock:
      GLOBAL:
        BUY:
          Initial_Amount: -1
          Restock_Time: 0
        SELL:
          Initial_Amount: -1
          Restock_Time: 0
      PLAYER:
        BUY:
          Initial_Amount: -1
          Restock_Time: 0
        SELL:
          Initial_Amount: -1
          Restock_Time: 0
    Content:
      Commands: []
      Item: 5000080016ip002dmmirj5cdp62pjk79pn8rreclfmgrr518006t31cs1g01i4c5mm2pr5000000000400agrfeln78080
      Preview: 5000080016ip002dmmirj5cdp62pjk79pn8rreclfmgrr518006t31cs1g01i4c5mm2pr5000000000400agrfeln78080
  26533024-19f0-4ab8-b45a-6faa07b60b08:
    Shop_View:
      Slot: 43
      Page: 1
    Discount:
      Allowed: true
    Reward: {}
    Currency: vault
    Item_Meta_Enabled: true
    Price:
      Type: FLAT
      BUY: 50.0
      SELL: 20.0
    Stock:
      GLOBAL:
        BUY:
          Initial_Amount: -1
          Restock_Time: 0
        SELL:
          Initial_Amount: -1
          Restock_Time: 0
      PLAYER:
        BUY:
          Initial_Amount: -1
          Restock_Time: 0
        SELL:
          Initial_Amount: -1
          Restock_Time: 0
    Content:
      Commands: []
      Item: a0000g002d5i005bdd5n6aoric5j78ej4d5gmqrrechfm2u3518006t31cs1g01i4c5mm2pr5000000000400agrfeln78080
      Preview: a0000g002d5i005bdd5n6aoric5j78ej4d5gmqrrechfm2u3518006t31cs1g01i4c5mm2pr5000000000400agrfeln78080
  6a2ccada-e6b0-40a4-b27c-bfbf599ca7b4:
    Shop_View:
      Slot: 5
      Page: 1
    Discount:
      Allowed: true
    Reward: {}
    Currency: vault
    Item_Meta_Enabled: true
    Price:
      Type: FLAT
      BUY: 50.0
      SELL: 20.0
    Stock:
      GLOBAL:
        BUY:
          Initial_Amount: -1
          Restock_Time: 0
        SELL:
          Initial_Amount: -1
          Restock_Time: 0
      PLAYER:
        BUY:
          Initial_Amount: -1
          Restock_Time: 0
        SELL:
          Initial_Amount: -1
          Restock_Time: 0
    Content:
      Commands: []
      Item: a0000g002d5i005bdd5n6aoric5j78ej6d5pmgqbectfn4rr418006t31cs1g01i4c5mm2pr5000000000400agrfeln78080
      Preview: a0000g002d5i005bdd5n6aoric5j78ej6d5pmgqbectfn4rr418006t31cs1g01i4c5mm2pr5000000000400agrfeln78080
  96444a60-b36c-472b-81ed-7441ba2cb15f:
    Shop_View:
      Slot: 10
      Page: 1
    Discount:
      Allowed: true
    Reward: {}
    Currency: vault
    Item_Meta_Enabled: true
    Price:
      Type: FLAT
      BUY: 50.0
      SELL: 20.0
    Stock:
      GLOBAL:
        BUY:
          Initial_Amount: -1
          Restock_Time: 0
        SELL:
          Initial_Amount: -1
          Restock_Time: 0
      PLAYER:
        BUY:
          Initial_Amount: -1
          Restock_Time: 0
        SELL:
          Initial_Amount: -1
          Restock_Time: 0
    Content:
      Commands: []
      Item: k00010004qb400bmqqbeclhn4ob6egt7errfchimsnrjd1nncpbc18006t31cs1g01i4c5mm2pr5000000000400agrfeln78080
      Preview: k00010004qb400bmqqbeclhn4ob6egt7errfchimsnrjd1nncpbc18006t31cs1g01i4c5mm2pr5000000000400agrfeln78080
  8dc2bc13-6f2a-4d6b-b603-1de403a2e834:
    Shop_View:
      Slot: 12
      Page: 1
    Discount:
      Allowed: true
    Reward: {}
    Currency: vault
    Item_Meta_Enabled: true
    Price:
      Type: FLAT
      BUY: 50.0
      SELL: 20.0
    Stock:
      GLOBAL:
        BUY:
          Initial_Amount: -1
          Restock_Time: 0
        SELL:
          Initial_Amount: -1
          Restock_Time: 0
      PLAYER:
        BUY:
          Initial_Amount: -1
          Restock_Time: 0
        SELL:
          Initial_Amount: -1
          Restock_Time: 0
    Content:
      Commands: []
      Item: 2g0004000j9cg01crb9dpim6sj1cpq3ksrkdtn6anrjd1nncpbc18006t31cs1g01i4c5mm2pr5000000000400agrfeln78080
      Preview: 2g0004000j9cg01crb9dpim6sj1cpq3ksrkdtn6anrjd1nncpbc18006t31cs1g01i4c5mm2pr5000000000400agrfeln78080
  aa020808-32b4-488c-ad9e-462fd0fc92d1:
    Shop_View:
      Slot: 19
      Page: 1
    Discount:
      Allowed: true
    Reward: {}
    Currency: vault
    Item_Meta_Enabled: true
    Price:
      Type: FLAT
      BUY: 50.0
      SELL: 20.0
    Stock:
      GLOBAL:
        BUY:
          Initial_Amount: -1
          Restock_Time: 0
        SELL:
          Initial_Amount: -1
          Restock_Time: 0
      PLAYER:
        BUY:
          Initial_Amount: -1
          Restock_Time: 0
        SELL:
          Initial_Amount: -1
          Restock_Time: 0
    Content:
      Commands: []
      Item: 5000080016ip0031mmirj5cdp62pjk79rmurr4cln5us39cdlm2u3518006t31cs1g01i4c5mm2pr5000000000400agrfeln78080
      Preview: 5000080016ip0031mmirj5cdp62pjk79rmurr4cln5us39cdlm2u3518006t31cs1g01i4c5mm2pr5000000000400agrfeln78080
  75939a4c-c441-4acc-a8eb-ea010e0f4373:
    Shop_View:
      Slot: 34
      Page: 1
    Discount:
      Allowed: true
    Reward: {}
    Currency: vault
    Item_Meta_Enabled: true
    Price:
      Type: FLAT
      BUY: 50.0
      SELL: 20.0
    Stock:
      GLOBAL:
        BUY:
          Initial_Amount: -1
          Restock_Time: 0
        SELL:
          Initial_Amount: -1
          Restock_Time: 0
      PLAYER:
        BUY:
          Initial_Amount: -1
          Restock_Time: 0
        SELL:
          Initial_Amount: -1
          Restock_Time: 0
    Content:
      Commands: []
      Item: a0000g002d5i005bdd5n6aoric5j78ej4d5gmqrrechfmgrr518006t31cs1g01i4c5mm2pr5000000000400agrfeln78080
      Preview: a0000g002d5i005bdd5n6aoric5j78ej4d5gmqrrechfmgrr518006t31cs1g01i4c5mm2pr5000000000400agrfeln78080
  58e45f95-fe4b-49e5-9b94-5e2bd78a0066:
    Shop_View:
      Slot: 28
      Page: 1
    Discount:
      Allowed: true
    Reward: {}
    Currency: vault
    Item_Meta_Enabled: true
    Price:
      Type: FLAT
      BUY: 50.0
      SELL: 20.0
    Stock:
      GLOBAL:
        BUY:
          Initial_Amount: -1
          Restock_Time: 0
        SELL:
          Initial_Amount: -1
          Restock_Time: 0
      PLAYER:
        BUY:
          Initial_Amount: -1
          Restock_Time: 0
        SELL:
          Initial_Amount: -1
          Restock_Time: 0
    Content:
      Commands: []
      Item: 1800020009km800kdlkmspb3e9gmct1qetnmup35dpfmgrr518006t31cs1g01i4c5mm2pr5000000000400agrfeln78080
      Preview: 1800020009km800kdlkmspb3e9gmct1qetnmup35dpfmgrr518006t31cs1g01i4c5mm2pr5000000000400agrfeln78080
  b3716aae-8bb3-4aa4-abd0-b7bb1a7f70f5:
    Shop_View:
      Slot: 41
      Page: 1
    Discount:
      Allowed: true
    Reward: {}
    Currency: vault
    Item_Meta_Enabled: true
    Price:
      Type: FLAT
      BUY: 50.0
      SELL: 20.0
    Stock:
      GLOBAL:
        BUY:
          Initial_Amount: -1
          Restock_Time: 0
        SELL:
          Initial_Amount: -1
          Restock_Time: 0
      PLAYER:
        BUY:
          Initial_Amount: -1
          Restock_Time: 0
        SELL:
          Initial_Amount: -1
          Restock_Time: 0
    Content:
      Commands: []
      Item: k00010004qb40096qqbeclhn4ob6egt6isjfdpfm2u3518006t31cs1g01i4c5mm2pr5000000000400agrfeln78080
      Preview: k00010004qb40096qqbeclhn4ob6egt6isjfdpfm2u3518006t31cs1g01i4c5mm2pr5000000000400agrfeln78080
  1c458772-0d44-4ef4-b3b9-14d6acf58481:
    Shop_View:
      Slot: 1
      Page: 1
    Discount:
      Allowed: true
    Reward: {}
    Currency: vault
    Item_Meta_Enabled: true
    Price:
      Type: FLAT
      BUY: 50.0
      SELL: 20.0
    Stock:
      GLOBAL:
        BUY:
          Initial_Amount: -1
          Restock_Time: 0
        SELL:
          Initial_Amount: -1
          Restock_Time: 0
      PLAYER:
        BUY:
          Initial_Amount: -1
          Restock_Time: 0
        SELL:
          Initial_Amount: -1
          Restock_Time: 0
    Content:
      Commands: []
      Item: 2g0004000j9cg012rb9dpim6sj1cpq3korfdlo62srj0400agrfeln78080
      Preview: 2g0004000j9cg012rb9dpim6sj1cpq3korfdlo62srj0400agrfeln78080
  7c370e9e-8e10-4d65-aa32-b7f799c94d49:
    Shop_View:
      Slot: 14
      Page: 1
    Discount:
      Allowed: true
    Reward: {}
    Currency: vault
    Item_Meta_Enabled: true
    Price:
      Type: FLAT
      BUY: 50.0
      SELL: 20.0
    Stock:
      GLOBAL:
        BUY:
          Initial_Amount: -1
          Restock_Time: 0
        SELL:
          Initial_Amount: -1
          Restock_Time: 0
      PLAYER:
        BUY:
          Initial_Amount: -1
          Restock_Time: 0
        SELL:
          Initial_Amount: -1
          Restock_Time: 0
    Content:
      Commands: []
      Item: a0000g002d5i005bdd5n6aoric5j78ej9e9nmsnrjd1nncpbc18006t31cs1g01i4c5mm2pr5000000000400agrfeln78080
      Preview: a0000g002d5i005bdd5n6aoric5j78ej9e9nmsnrjd1nncpbc18006t31cs1g01i4c5mm2pr5000000000400agrfeln78080
  471435d4-d217-4627-b381-93c8c8e88d83:
    Shop_View:
      Slot: 39
      Page: 1
    Discount:
      Allowed: true
    Reward: {}
    Currency: vault
    Item_Meta_Enabled: true
    Price:
      Type: FLAT
      BUY: 50.0
      SELL: 20.0
    Stock:
      GLOBAL:
        BUY:
          Initial_Amount: -1
          Restock_Time: 0
        SELL:
          Initial_Amount: -1
          Restock_Time: 0
      PLAYER:
        BUY:
          Initial_Amount: -1
          Restock_Time: 0
        SELL:
          Initial_Amount: -1
          Restock_Time: 0
    Content:
      Commands: []
      Item: 5000080016ip002dmmirj5cdp62pjk79pn8rreclfm2u3518006t31cs1g01i4c5mm2pr5000000000400agrfeln78080
      Preview: 5000080016ip002dmmirj5cdp62pjk79pn8rreclfm2u3518006t31cs1g01i4c5mm2pr5000000000400agrfeln78080
