List:
  a7fc2d3e-2724-42ab-8cf4-bf1f64fccf96:
    Content:
      Item: 2g0004000j9cg01mrb9dpim6sj1cpq3kpboe1in4qb5dphmanr2dtq78r350400agrfeln781g0
    Item_Meta_Enabled: false
    Allowed_Ranks: []
    Stock:
      GLOBAL:
        BUY:
          Initial_Amount: -1
          Restock_Time: 0
        SELL:
          Initial_Amount: -1
          Restock_Time: 0
      PLAYER:
        BUY:
          Initial_Amount: 24
          Restock_Time: -1
        SELL:
          Initial_Amount: -1
          Restock_Time: 0
    Currency: vault
    Price:
      Type: FLAT
      SELL: 25.0
      BUY: 100.0
    Rotation:
      Chance: 50.0
  44c70d90-5f77-4219-b23f-4816daf9381c:
    Content:
      Item: 5000080016ip002dmmirj5cdp62pjk79imsp35e9fmaub50400agrfeln780g0
    Item_Meta_Enabled: false
    Allowed_Ranks: []
    Stock:
      GLOBAL:
        BUY:
          Initial_Amount: -1
          Restock_Time: 0
        SELL:
          Initial_Amount: -1
          Restock_Time: 0
      PLAYER:
        BUY:
          Initial_Amount: -1
          Restock_Time: 0
        SELL:
          Initial_Amount: -1
          Restock_Time: 0
    Currency: vault
    Price:
      Type: FLAT
      SELL: 25.0
      BUY: 100.0
    Rotation:
      Chance: 50.0
  a02bb55e-c904-4b82-9187-26aaa571bdc5:
    Content:
      Item: 1800020009km800kdlkmspb3e9gmct1qd5p6urivd5n6errk0400agrfeln78400
    Item_Meta_Enabled: false
    Allowed_Ranks: []
    Stock:
      GLOBAL:
        BUY:
          Initial_Amount: -1
          Restock_Time: 0
        SELL:
          Initial_Amount: -1
          Restock_Time: 0
      PLAYER:
        BUY:
          Initial_Amount: -1
          Restock_Time: 0
        SELL:
          Initial_Amount: -1
          Restock_Time: 0
    Currency: vault
    Price:
      Type: FLAT
      SELL: 25.0
      BUY: 100.0
    Rotation:
      Chance: 50.0
  075b3d40-fe37-4bde-b4b3-b8aafd010f7b:
    Content:
      Item: 1800020009km800kdlkmspb3e9gmct1qctnmop2vd5n6errk0400agrfeln78100
    Item_Meta_Enabled: false
    Allowed_Ranks: []
    Stock:
      GLOBAL:
        BUY:
          Initial_Amount: -1
          Restock_Time: 0
        SELL:
          Initial_Amount: -1
          Restock_Time: 0
      PLAYER:
        BUY:
          Initial_Amount: -1
          Restock_Time: 0
        SELL:
          Initial_Amount: -1
          Restock_Time: 0
    Currency: vault
    Price:
      Type: FLAT
      SELL: 25.0
      BUY: 100.0
    Rotation:
      Chance: 50.0
  960df15f-607a-41fa-8eac-9198464838ca:
    Content:
      Item: 2g0004000j9cg01crb9dpim6sj1cpq3kr31e1kn6nrcc5t7ar390400agrfeln78200
    Item_Meta_Enabled: false
    Allowed_Ranks: []
    Stock:
      GLOBAL:
        BUY:
          Initial_Amount: -1
          Restock_Time: 0
        SELL:
          Initial_Amount: -1
          Restock_Time: 0
      PLAYER:
        BUY:
          Initial_Amount: -1
          Restock_Time: 0
        SELL:
          Initial_Amount: -1
          Restock_Time: 0
    Currency: vault
    Price:
      Type: FLAT
      SELL: 25.0
      BUY: 100.0
    Rotation:
      Chance: 50.0
  9689eb35-93d9-4559-ae78-7fd46d6028f1:
    Content:
      Item: 1800020009km800fdlkmspb3e9gmct1qcpm6irjk0400agrfeln780o0
    Item_Meta_Enabled: false
    Allowed_Ranks: []
    Stock:
      GLOBAL:
        BUY:
          Initial_Amount: -1
          Restock_Time: 0
        SELL:
          Initial_Amount: -1
          Restock_Time: 0
      PLAYER:
        BUY:
          Initial_Amount: -1
          Restock_Time: 0
        SELL:
          Initial_Amount: -1
          Restock_Time: 0
    Currency: vault
    Price:
      Type: FLAT
      SELL: 25.0
      BUY: 100.0
    Rotation:
      Chance: 50.0
  ff29e9bb-0f2d-4c49-9662-fc2519e2595c:
    Content:
      Item: k00010004qb4006mqqbeclhn4ob6egt6apr70400agrfeln78100
    Item_Meta_Enabled: false
    Allowed_Ranks: []
    Stock:
      GLOBAL:
        BUY:
          Initial_Amount: -1
          Restock_Time: 0
        SELL:
          Initial_Amount: -1
          Restock_Time: 0
      PLAYER:
        BUY:
          Initial_Amount: -1
          Restock_Time: 0
        SELL:
          Initial_Amount: -1
          Restock_Time: 0
    Currency: vault
    Price:
      Type: FLAT
      SELL: 25.0
      BUY: 100.0
    Rotation:
      Chance: 50.0
  964ec2e4-421b-4af1-8d0a-5fea37d3634e:
    Content:
      Item: k00010004qb4006mqqbeclhn4ob6egt78rjk0400agrfeln78280
    Item_Meta_Enabled: false
    Allowed_Ranks: []
    Stock:
      GLOBAL:
        BUY:
          Initial_Amount: -1
          Restock_Time: 0
        SELL:
          Initial_Amount: -1
          Restock_Time: 0
      PLAYER:
        BUY:
          Initial_Amount: -1
          Restock_Time: 0
        SELL:
          Initial_Amount: -1
          Restock_Time: 0
    Currency: vault
    Price:
      Type: FLAT
      SELL: 25.0
      BUY: 100.0
    Rotation:
      Chance: 50.0
  017dc527-66a2-4419-939d-5bb4b759d38b:
    Content:
      Item: a0000g002d5i0043dd5n6aoric5j78ej3c5p74rrk0400agrfeln781g0
    Item_Meta_Enabled: false
    Allowed_Ranks: []
    Stock:
      GLOBAL:
        BUY:
          Initial_Amount: -1
          Restock_Time: 0
        SELL:
          Initial_Amount: -1
          Restock_Time: 0
      PLAYER:
        BUY:
          Initial_Amount: -1
          Restock_Time: 0
        SELL:
          Initial_Amount: -1
          Restock_Time: 0
    Currency: vault
    Price:
      Type: FLAT
      SELL: 25.0
      BUY: 100.0
    Rotation:
      Chance: 50.0
  493f43c4-ea7e-446e-a273-6c0fa4597d34:
    Content:
      Item: a0000g002d5i005bdd5n6aoric5j78ej7dtm68nreeljmepbk0400agrfeln78080
    Item_Meta_Enabled: false
    Allowed_Ranks: []
    Stock:
      GLOBAL:
        BUY:
          Initial_Amount: -1
          Restock_Time: 0
        SELL:
          Initial_Amount: -1
          Restock_Time: 0
      PLAYER:
        BUY:
          Initial_Amount: -1
          Restock_Time: 0
        SELL:
          Initial_Amount: -1
          Restock_Time: 0
    Currency: vault
    Price:
      Type: FLAT
      SELL: 25.0
      BUY: 100.0
    Rotation:
      Chance: 50.0
  56bf15ba-ff20-4267-8dad-52a3bd93aaa9:
    Content:
      Item: a0000g002d5i005bdd5n6aoric5j78ej9e9nmsnreeljmepbk0400agrfeln78080
    Item_Meta_Enabled: false
    Allowed_Ranks: []
    Stock:
      GLOBAL:
        BUY:
          Initial_Amount: -1
          Restock_Time: 0
        SELL:
          Initial_Amount: -1
          Restock_Time: 0
      PLAYER:
        BUY:
          Initial_Amount: -1
          Restock_Time: 0
        SELL:
          Initial_Amount: -1
          Restock_Time: 0
    Currency: vault
    Price:
      Type: FLAT
      SELL: 25.0
      BUY: 100.0
    Rotation:
      Chance: 50.0
  4ac10a11-ae44-4ab5-9c49-f8f9d224164b:
    Content:
      Item: 1800020009km800fdlkmspb3e9gmct1qetk6aobk0400agrfeln78080
    Item_Meta_Enabled: false
    Allowed_Ranks: []
    Stock:
      GLOBAL:
        BUY:
          Initial_Amount: -1
          Restock_Time: 0
        SELL:
          Initial_Amount: -1
          Restock_Time: 0
      PLAYER:
        BUY:
          Initial_Amount: -1
          Restock_Time: 0
        SELL:
          Initial_Amount: -1
          Restock_Time: 0
    Currency: vault
    Price:
      Type: FLAT
      SELL: 25.0
      BUY: 100.0
    Rotation:
      Chance: 50.0
  64e1ea49-c8ae-4f1d-89ff-8ef2a63e91fa:
    Content:
      Item: 1800020009km800fdlkmspb3e9gmct1qedq6iorb0400agrfeln78080
    Item_Meta_Enabled: false
    Allowed_Ranks: []
    Stock:
      GLOBAL:
        BUY:
          Initial_Amount: -1
          Restock_Time: 0
        SELL:
          Initial_Amount: -1
          Restock_Time: 0
      PLAYER:
        BUY:
          Initial_Amount: -1
          Restock_Time: 0
        SELL:
          Initial_Amount: -1
          Restock_Time: 0
    Currency: vault
    Price:
      Type: FLAT
      SELL: 25.0
      BUY: 100.0
    Rotation:
      Chance: 50.0
  2731356c-af45-4dfc-a5f1-b1f72e7d92bf:
    Content:
      Item: 2g0004000j9cg012rb9dpim6sj1cpq3kr35c5q6gpbi0400agrfeln78080
    Item_Meta_Enabled: false
    Allowed_Ranks: []
    Stock:
      GLOBAL:
        BUY:
          Initial_Amount: -1
          Restock_Time: 0
        SELL:
          Initial_Amount: -1
          Restock_Time: 0
      PLAYER:
        BUY:
          Initial_Amount: -1
          Restock_Time: 0
        SELL:
          Initial_Amount: -1
          Restock_Time: 0
    Currency: vault
    Price:
      Type: FLAT
      SELL: 25.0
      BUY: 100.0
    Rotation:
      Chance: 50.0
  def69aa6-1af0-4bdf-9a0e-ccdf71dc6ff2:
    Content:
      Item: 2g0004000j9cg01crb9dpim6sj1cpq3korfe1o6asivd5n6errk0400agrfeln78080
    Item_Meta_Enabled: false
    Allowed_Ranks: []
    Stock:
      GLOBAL:
        BUY:
          Initial_Amount: -1
          Restock_Time: 0
        SELL:
          Initial_Amount: -1
          Restock_Time: 0
      PLAYER:
        BUY:
          Initial_Amount: -1
          Restock_Time: 0
        SELL:
          Initial_Amount: -1
          Restock_Time: 0
    Currency: vault
    Price:
      Type: FLAT
      SELL: 25.0
      BUY: 100.0
    Rotation:
      Chance: 50.0
  1a3e6ede-76de-41c9-aea2-8c1aedd883a8:
    Content:
      Item: k00010004qb40096qqbeclhn4ob6egt6esj1f5fm8ub50400agrfeln78080
    Item_Meta_Enabled: false
    Allowed_Ranks: []
    Stock:
      GLOBAL:
        BUY:
          Initial_Amount: -1
          Restock_Time: 0
        SELL:
          Initial_Amount: -1
          Restock_Time: 0
      PLAYER:
        BUY:
          Initial_Amount: -1
          Restock_Time: 0
        SELL:
          Initial_Amount: -1
          Restock_Time: 0
    Currency: vault
    Price:
      Type: FLAT
      SELL: 25.0
      BUY: 100.0
    Rotation:
      Chance: 50.0
  9e396c0a-e9d3-420a-9d66-c1fcad64b997:
    Content:
      Item: 5000080016ip001pmmirj5cdp62pjk79h6urrb0400agrfeln78080
    Item_Meta_Enabled: false
    Allowed_Ranks: []
    Stock:
      GLOBAL:
        BUY:
          Initial_Amount: -1
          Restock_Time: 0
        SELL:
          Initial_Amount: -1
          Restock_Time: 0
      PLAYER:
        BUY:
          Initial_Amount: -1
          Restock_Time: 0
        SELL:
          Initial_Amount: -1
          Restock_Time: 0
    Currency: vault
    Price:
      Type: FLAT
      SELL: 25.0
      BUY: 100.0
    Rotation:
      Chance: 50.0
  a83432bf-32ee-44a3-8b46-78fcb8c697a4:
    Content:
      Item: 2g0004000j9cg01crb9dpim6sj1cpq3kprcc5pn6nr2dtq78r350400agrfeln78080
    Item_Meta_Enabled: false
    Allowed_Ranks: []
    Stock:
      GLOBAL:
        BUY:
          Initial_Amount: -1
          Restock_Time: 0
        SELL:
          Initial_Amount: -1
          Restock_Time: 0
      PLAYER:
        BUY:
          Initial_Amount: -1
          Restock_Time: 0
        SELL:
          Initial_Amount: -1
          Restock_Time: 0
    Currency: vault
    Price:
      Type: FLAT
      SELL: 25.0
      BUY: 100.0
    Rotation:
      Chance: 50.0
  8e44f032-7542-4d0c-907b-745810aef944:
    Content:
      Item: a0000g002d5i005bdd5n6aoric5j78ejdclm6urivedm6ior50400agrfeln78080
    Item_Meta_Enabled: false
    Allowed_Ranks: []
    Stock:
      GLOBAL:
        BUY:
          Initial_Amount: -1
          Restock_Time: 0
        SELL:
          Initial_Amount: -1
          Restock_Time: 0
      PLAYER:
        BUY:
          Initial_Amount: -1
          Restock_Time: 0
        SELL:
          Initial_Amount: -1
          Restock_Time: 0
    Currency: vault
    Price:
      Type: FLAT
      SELL: 25.0
      BUY: 100.0
    Rotation:
      Chance: 50.0
  98fea7f4-707d-499d-baa1-8de6da392127:
    Content:
      Item: 5000080016ip0031mmirj5cdp62pjk79n62tbkd5m7asqvedk6ar3c0400agrfeln78080
    Item_Meta_Enabled: false
    Allowed_Ranks: []
    Stock:
      GLOBAL:
        BUY:
          Initial_Amount: -1
          Restock_Time: 0
        SELL:
          Initial_Amount: -1
          Restock_Time: 0
      PLAYER:
        BUY:
          Initial_Amount: -1
          Restock_Time: 0
        SELL:
          Initial_Amount: -1
          Restock_Time: 0
    Currency: vault
    Price:
      Type: FLAT
      SELL: 25.0
      BUY: 100.0
    Rotation:
      Chance: 50.0
  1b374a65-2662-4657-9ef6-4e101a0c477a:
    Content:
      Item: a0000g002d5i006jdd5n6aoric5j78ej8clgn4t2vdtj5ut38clfn6pb10400agrfeln78080
    Item_Meta_Enabled: false
    Allowed_Ranks: []
    Stock:
      GLOBAL:
        BUY:
          Initial_Amount: -1
          Restock_Time: 0
        SELL:
          Initial_Amount: -1
          Restock_Time: 0
      PLAYER:
        BUY:
          Initial_Amount: -1
          Restock_Time: 0
        SELL:
          Initial_Amount: -1
          Restock_Time: 0
    Currency: vault
    Price:
      Type: FLAT
      SELL: 25.0
      BUY: 100.0
    Rotation:
      Chance: 50.0
  2b326ff3-c43d-4fbb-9e97-87be0092b23f:
    Content:
      Item: a0000g002d5i005bdd5n6aoric5j78ej6d5p6anr3d1gn4pr50400agrfeln78080
    Item_Meta_Enabled: false
    Allowed_Ranks: []
    Stock:
      GLOBAL:
        BUY:
          Initial_Amount: -1
          Restock_Time: 0
        SELL:
          Initial_Amount: -1
          Restock_Time: 0
      PLAYER:
        BUY:
          Initial_Amount: -1
          Restock_Time: 0
        SELL:
          Initial_Amount: -1
          Restock_Time: 0
    Currency: vault
    Price:
      Type: FLAT
      SELL: 25.0
      BUY: 100.0
    Rotation:
      Chance: 50.0
  aace5546-92b1-4e5f-ae5a-23a6be4c9c75:
    Content:
      Item: k00010004qb40096qqbeclhn4ob6egt6sobdclfn8ob70400agrfeln78080
    Item_Meta_Enabled: false
    Allowed_Ranks: []
    Stock:
      GLOBAL:
        BUY:
          Initial_Amount: -1
          Restock_Time: 0
        SELL:
          Initial_Amount: -1
          Restock_Time: 0
      PLAYER:
        BUY:
          Initial_Amount: -1
          Restock_Time: 0
        SELL:
          Initial_Amount: -1
          Restock_Time: 0
    Currency: vault
    Price:
      Type: FLAT
      SELL: 25.0
      BUY: 100.0
    Rotation:
      Chance: 50.0
  f2a3e006-8acf-477e-91a0-291753bf28a7:
    Content:
      Item: 1800020009km800fdlkmspb3e9gmct1qc5o70r350400agrfeln78080
    Item_Meta_Enabled: false
    Allowed_Ranks: []
    Stock:
      GLOBAL:
        BUY:
          Initial_Amount: -1
          Restock_Time: 0
        SELL:
          Initial_Amount: -1
          Restock_Time: 0
      PLAYER:
        BUY:
          Initial_Amount: -1
          Restock_Time: 0
        SELL:
          Initial_Amount: -1
          Restock_Time: 0
    Currency: vault
    Price:
      Type: FLAT
      SELL: 25.0
      BUY: 100.0
    Rotation:
      Chance: 50.0
  1e0c5f7d-88cb-496a-84b5-6377f3f3f823:
    Content:
      Item: 5000080016ip001pmmirj5cdp62pjk79m6aob40400agrfeln78080
    Item_Meta_Enabled: false
    Allowed_Ranks: []
    Stock:
      GLOBAL:
        BUY:
          Initial_Amount: -1
          Restock_Time: 0
        SELL:
          Initial_Amount: -1
          Restock_Time: 0
      PLAYER:
        BUY:
          Initial_Amount: -1
          Restock_Time: 0
        SELL:
          Initial_Amount: -1
          Restock_Time: 0
    Currency: vault
    Price:
      Type: FLAT
      SELL: 25.0
      BUY: 100.0
    Rotation:
      Chance: 50.0
  88a3f22c-191b-4c29-84b4-2122b9b1a46d:
    Content:
      Item: 1800020009km800kdlkmspb3e9gmct1qcdnmuqr5chfm6rr40400agrfeln78080
    Item_Meta_Enabled: false
    Allowed_Ranks: []
    Stock:
      GLOBAL:
        BUY:
          Initial_Amount: -1
          Restock_Time: 0
        SELL:
          Initial_Amount: -1
          Restock_Time: 0
      PLAYER:
        BUY:
          Initial_Amount: -1
          Restock_Time: 0
        SELL:
          Initial_Amount: -1
          Restock_Time: 0
    Currency: vault
    Price:
      Type: FLAT
      SELL: 25.0
      BUY: 100.0
    Rotation:
      Chance: 50.0
  ec40fdcc-001a-41ae-95af-9e9d11203667:
    Content:
      Item: 1800020009km800kdlkmspb3e9gmct1qedo6ip35e9fmaub50400agrfeln78080
    Item_Meta_Enabled: false
    Allowed_Ranks: []
    Stock:
      GLOBAL:
        BUY:
          Initial_Amount: -1
          Restock_Time: 0
        SELL:
          Initial_Amount: -1
          Restock_Time: 0
      PLAYER:
        BUY:
          Initial_Amount: -1
          Restock_Time: 0
        SELL:
          Initial_Amount: -1
          Restock_Time: 0
    Currency: vault
    Price:
      Type: FLAT
      SELL: 25.0
      BUY: 100.0
    Rotation:
      Chance: 50.0
