Name: '&x&2&c&c&d&4&2&lH&x&3&0&c&c&4&6&lo&x&3&5&c&c&4&a&ls&x&3&a&c&c&4&e&lt&x&3&f&c&c&5&2&li&x&4&4&c&c&5&6&ll&x&4&9&c&c&5&b&le&x&4&e&c&c&5&f&l &x&5&3&c&c&6&3&lM&x&5&7&c&c&6&7&lo&x&5&c&c&c&6&b&lb&x&6&1&c&c&7&0&l &x&6&6&c&c&7&4&lL&x&6&b&c&c&7&8&lo&x&7&0&c&c&7&c&lo&x&7&5&c&c&8&0&lt'
Pages: 4
Permission_Required: false
Transaction_Allowed:
  SELL: true
  BUY: true
Citizens:
  Attached_NPC: ''
Description:
- '&x&d&4&d&9&d&8Everything related to'
- '&x&d&4&d&9&d&8hostile mobs and their loot.'
Icon:
  Material: CREEPER_HEAD
