name: ExcellentShop
main: su.nightexpress.nexshop.ExcellentShop
version: '${project.version}'
description: Advanced 3 in 1 shop plugin with a lot of cool features!
author: NightExpress
depend: [ NexEngine ]
softdepend:
  - Vault
  - Citizens
  - PlayerPoints
  - WorldGuard
  - Lands
  - GemsEconomy
  - CoinsEngine
  - GriefPrevention
  - EliteMobs
api-version: 1.17