name: ExcellentShop
main: su.nightexpress.nexshop.ShopPlugin
version: '${project.version}'
description: Advanced 4 in 1 shop plugin with a lot of cool features!
author: NightExpress
depend: [ nightcore, EconomyBridge ]
softdepend:
  - Citizens
  - WorldGuard
  - Lands
  - Kingdoms
  - AdvancedRegionMarket
  - GriefPrevention
  - Oraxen
  - ItemsAdder
  - Nexo
  - ExecutableItems
  - SCore
  - MMOItems
  - ExcellentCrates
  - PlaceholderAPI
  - ProtocolLib
  - packetevents
api-version: 1.18