Name: '<gradient:#ff69bc>&lPeaceful Mob Shop</gradient:#ffbee2>'
Description:
- '#d4d9d8Everything related to'
- '#d4d9d8peaceful mobs and their loot.'
Pages: 3
Permission_Required: false
Citizens:
  Attached_NPC: ''
Transaction_Allowed:
  SELL: true
  BUY: true
Icon:
  Material: PLAYER_HEAD
  Head_Texture: eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMWEzNzFhMDZlYTc4NThmODlkMjdjYzEwNTVjMzE3YjIzZjEwNWM5MTI1YmM1MTZkMzg5MWFhNGM4MzVjMjk5In19fQ==
